markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

title : developer.parallax.com
tagline: The home of Parallax open-source development
author :
  name : Parallax, Inc.
  website : http://www.parallax.com
  email : support@parallax.com
  github : parallaxinc
  twitter : ParallaxInc
  feedburner : feedname

production_url : http://parallaxinc.github.io

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : false
   
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-285614-1'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik

  sharing :
    provider : false
    
collections:
    projects:
        output: true
        permalink: /:path/

defaults:
    - scope:
          collection: projects
      values:
          layout: project
          type: other
